### ISSUE TITLE
First update is not published to GeoBroker

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#26]
The internal transport mechanism does not provide an update event on creation of an incident.

Mitigation: Save a created incident 2 times.

@fs1 fyi, known limitation

**Comment by robo-w** [comment]
Log file says:
`
2018-05-09T20:22:41,890; [ForkJoinPool.commonPool-worker-0]; ERROR; a.w.c.p.g.GeobrokerIncidentEntityListener; Uncaught exception in GeoBroker plugin.
java.lang.NullPointerException
        at at.wrk.coceso.plugin.geobroker.external.ExternalIncidentFactory.createExternalIncident(ExternalIncidentFactory.java:47) ~[coceso-geobroker-2.3.0-SNAPSHOT.jar:?]
        at at.wrk.coceso.plugin.geobroker.GeobrokerIncidentEntityListener.lambda$entityChanged$0(GeobrokerIncidentEntityListener.java:41) ~[coceso-geobroker-2.3.0-SNAPSHOT.jar:?]
        at at.wrk.coceso.plugin.geobroker.GeobrokerIncidentEntityListener.executeSafely(GeobrokerIncidentEntityListener.java:61) ~[coceso-geobroker-2.3.0-SNAPSHOT.jar:?]
        at at.wrk.coceso.plugin.geobroker.GeobrokerIncidentEntityListener.entityChanged(GeobrokerIncidentEntityListener.java:40) ~[coceso-geobroker-2.3.0-SNAPSHOT.jar:?]
        at at.wrk.coceso.plugin.geobroker.GeobrokerIncidentEntityListener.entityChanged(GeobrokerIncidentEntityListener.java:20) ~[coceso-geobroker-2.3.0-SNAPSHOT.jar:?]
        at at.wrk.coceso.entityevent.impl.EntityEventHandlerImpl.lambda$entityChanged$0(EntityEventHandlerImpl.java:47) ~[coceso-service-impl-2.2.1.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_171]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) [?:1.8.0_171]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_171]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_171]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_171]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_171]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_171]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_171]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_171]
`
