### ISSUE TITLE
User import throws error if unknown column is present

### ISSUE THREAD

**Issue by robo-w** [wrk-fmd/CoCeSo#6]
`03-Jan-2018 20:27:07.194 SEVERE [http-nio-127.0.0.1-8080-exec-5] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [dispatcher] in context wi
th path [/coceso] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Mapping for DNr. not found, expected one of [Kategorien;
Firma;Anrede;Titel;Nachname;Vorname;Autotelefon;Namenszusatz;Abteilung;Stra�e Privat;Postleitzahl Privat;Ort Privat;B�ro;Telefon gesch�ftlich;Telefon Privat;Telefon gesch�ftl
ich 2;Mobiltelefon;Weiteres Telefon;Mobiltelefon 2;e-mail privat;E-Mail 2;E-Mail 3;Fax gesch�ftlich;Fax Privat;weiteres Fax;Notruf Pager WRK;Pager;Bereitschaft WRK;Tetra Funk
ger�t;]] with root cause
 java.lang.IllegalArgumentException: Mapping for DNr. not found, expected one of [Kategorien;Firma;Anrede;Titel;Nachname;Vorname;Autotelefon;Namenszusatz;Abteilung;Stra�e Pri
vat;Postleitzahl Privat;Ort Privat;B�ro;Telefon gesch�ftlich;Telefon Privat;Telefon gesch�ftlich 2;Mobiltelefon;Weiteres Telefon;Mobiltelefon 2;e-mail privat;E-Mail 2;E-Mail
3;Fax gesch�ftlich;Fax Privat;weiteres Fax;Notruf Pager WRK;Pager;Bereitschaft WRK;Tetra Funkger�t;]
        at org.apache.commons.csv.CSVRecord.get(CSVRecord.java:104)
        at at.wrk.coceso.niu.NiuUserImporter.updateUsers(NiuUserImporter.java:53)
        at at.wrk.coceso.service.impl.UserServiceImpl.importUsers(UserServiceImpl.java:178)`

**Comment by robo-w** [comment]
Cause was an invalid input CSV (export of third-party tool provided wrong data). Refactored NIU importer plugin to get better error message.
